spring:
  datasource:
    # Replace the placeholders or define the DATABRICKS_JDBC_URL environment variable.
    url: ${DATABRICKS_JDBC_URL:jdbc:databricks://<server-hostname>:443/default;transportMode=http;ssl=1;httpPath=<http-path>;AuthMech=3;UID=token;PWD=<your-personal-access-token>}
    driver-class-name: com.databricks.client.jdbc.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      idle-timeout: 30000
      connection-timeout: 30000
