spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/userdb?createDatabaseIfNotExist=true
    username: root
    password: 111111
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
server:
  port: 8082
