services:
  predixy:
    image: haandol/predixy
    container_name: predixy
    hostname: predixy
    command: predixy etc/predixy/conf/predixy.conf
    volumes:
      - ./conf/predixy:/etc/predixy/conf
      - ./predixy.log:/etc/logs/predixy.log
    ports:
      - "7009:7009"
    networks:
      - redis-cluster

  redis-0:
    image: redis:latest
    container_name: redis-0
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./conf/redis-0.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "7000:7000"
    networks:
      - redis-cluster

  redis-1:
    image: redis:latest
    container_name: redis-1
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./conf/redis-1.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "7001:7001"
    networks:
      - redis-cluster

  redis-2:
    image: redis:latest
    container_name: redis-2
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./conf/redis-2.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "7002:7002"
    networks:
      - redis-cluster

  redis-3:
    image: redis:latest
    container_name: redis-3
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./conf/redis-3.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "7003:7003"
    networks:
      - redis-cluster

  redis-4:
    image: redis:latest
    container_name: redis-4
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./conf/redis-4.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "7004:7004"
    networks:
      - redis-cluster

  redis-5:
    image: redis:latest
    container_name: redis-5
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./conf/redis-5.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "7005:7005"
    networks:
      - redis-cluster

  redis-cluster-init:
    image: redis:latest
    container_name: redis-cluster-init
    depends_on:
      - redis-0
      - redis-1
      - redis-2
      - redis-3
      - redis-4
      - redis-5
    entrypoint: >
      sh -c "
      sleep 5;
      echo 'yes' | redis-cli --cluster create
      redis-0:7000 redis-1:7001 redis-2:7002
      redis-3:7003 redis-4:7004 redis-5:7005
      --cluster-replicas 1"
    networks:
      - redis-cluster

networks:
  redis-cluster:
    driver: bridge