spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/userdb
    username: user
    password: pass
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
server:
  port: 8082
