spring:
  application:
    name: spring-clickhouse
  datasource:
    url: jdbc:ch://localhost:8123/default
    username: default
    password: "default"
    driver-class-name: com.clickhouse.jdbc.ClickHouseDriver
  flyway:
    enabled: true
    clean-disabled: false # 로컬/테스트 단계에서 스키마 재개발 편의성을 위해 clean 허용

